// <auto-generated />
namespace Hotel.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rebuild_logs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rebuild_logs));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011204252_rebuild_logs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
