// <auto-generated />
namespace Hotel.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_assessible : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_assessible));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171707293_add_assessible"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
