// <auto-generated />
namespace Hotel.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_unlucky_requests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_unlucky_requests));
        
        string IMigrationMetadata.Id
        {
            get { return "202003102017302_add_unlucky_requests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
